      SELECT 'Categories', Count(*) FROM [Northwind].[dbo].[Categories]
UNION SELECT 'CustomerCustomerDemo', Count(*) FROM [northwind].[dbo].[CustomerCustomerDemo]
UNION SELECT 'CustomerDemographics', Count(*) FROM [northwind].[dbo].[CustomerDemographics]
UNION SELECT 'Customers', Count(*) FROM [northwind].[dbo].[Customers]
UNION SELECT 'Employees', Count(*) FROM [northwind].[dbo].[Employees]
UNION SELECT 'EmployeeTerritories', Count(*) FROM [northwind].[dbo].[EmployeeTerritories]
UNION SELECT 'Order Details', Count(*) FROM [northwind].[dbo].[Order Details]
UNION SELECT 'Orders', Count(*) FROM [northwind].[dbo].[Orders]
UNION SELECT 'Products', Count(*) FROM [northwind].[dbo].[Products]
UNION SELECT 'Region', Count(*) FROM [northwind].[dbo].[Region]
UNION SELECT 'Shippers', Count(*) FROM [northwind].[dbo].[Shippers]
UNION SELECT 'Suppliers', Count(*) FROM [northwind].[dbo].[Suppliers]
UNION SELECT 'Territories', Count(*) FROM [northwind].[dbo].[Territories]